### ISSUE TITLE
Missing key files: preprocessed_KAIROS0/test.jsonl

### ISSUE THREAD

**Issue by OPilgrim** [xinyadu/memory_docie#1]
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    main()
  File "train.py", line 158, in main
    model = GenIEModel(args)
  File "/nfs/users/memory_docie/src/genie/model.py", line 111, in __init__
    with open("preprocessed_KAIROS0/test.jsonl", 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_KAIROS0/test.jsonl'

Excuse me, what is 'preprocessed_KAIROS0/test.jsonl' and how to obtain it?

**Comment by chiennv2000** [comment]
i got the same problem as you

**Comment by xxllp** [comment]
？？？？

**Comment by zhangyx0417** [comment]
the same！

**Comment by heng840** [comment]
please run the KAIROS_data_module.py first

**Comment by lby129** [comment]
i got the same problem. When I try to run the KAIROS_data_module.py I got a new problem:
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_KAIROS/train.jsonl'

**Comment by OPilgrim** [comment]
I've given up on KAIROS

**Comment by GreatYYX** [comment]
We had the code fixed while reproducing this work. Please refer to https://github.com/GreatYYX/csci662_memory_docie.
